.PHONY: all test clean

all:
	@echo "TODO: build rdma-file-send and rdma-file-recv"

test:
	@echo "TODO: run zero-copy file transfer tests"

clean:
	@echo "TODO: remove zero-copy file transfer build artifacts"
